# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install 
  displayName: 'npm install'

- script: |
    npm run build --prod
  displayName: 'npm build'
- task: AzureStaticWebApp@0
  inputs:
      app_location: "/app" 
      api_location: "api"
      output_location: "dist/catsify"
  env:
      azure_static_web_apps_api_token: $(deployment_token)